Feature/fbot 500 option to open web chat links to the same window
feedyou-ai/feedbot-webchat pull request #32
Opened 2021-06-18 08:26 UTC by janbadura

Added option to have persistent conversation and opening links in the  same window

2021-06-18 08:58 UTC, dvorakjan commented on src/App.tsx
> +
Here set new App & Chat prop `openUrlTarget: [new, same, same-domain]` + pls add to README.md

2021-06-18 08:58 UTC, dvorakjan commented on src/App.tsx
> +
```suggestion
```

2021-06-18 08:58 UTC, dvorakjan commented on src/App.tsx
> +      const dl = props.directLine || {}
```suggestion
      const directLine = props.directLine || {}
```

2021-06-18 08:58 UTC, dvorakjan commented on src/AdaptiveCardContainer.tsx
> +import {ChangeUrlAction} from "./ChangeUrlAction"
This `ChangeUrlAction` related stuff will probably won't be needed anymore.

2021-07-09 09:15 UTC, dvorakjan requested changes

2021-07-09 12:26 UTC, janbadura commented on src/App.tsx
> +        conversationId: directLine.conversationId || sessionStorage["feedbotConversationId"],
It's there if ```directLine.conversationId``` is undefined which can happen depending on the mode which is used, then it uses sessionStorage.

2021-07-20 10:50 UTC, merged