feat: FBOT-1000 added autosuggest functionality
feedyou-ai/feedbot-webchat pull request #63
Opened 2022-03-10 14:18 UTC by janbadura

2022-03-16 11:41 UTC, dvorakjan requested changes

2022-03-16 11:41 UTC, dvorakjan commented on samples/feedyou/modern.html
> +    <script src="../../botchat-es5.js"></script>
Tady by relativni cesty byt nemely. Ten prettier asi klidne nechme ale.

2022-03-16 11:41 UTC, dvorakjan commented on src/Shell.tsx
> +        `https://feedbot-test-demo-honza.azurewebsites.net/webchat/autosuggest/${replacedQueryString}`
Tady by to chtelo asi nemit URL napevno 😃 jak se to dela u toho mobiliho uploadu? tam se taky nejak URL skladat musi

2022-03-16 12:45 UTC, janbadura commented on samples/feedyou/modern.html
> +    <script src="../../botchat-es5.js"></script>
Sorry, nevím jak mi tam tohle proklouzlo

2022-03-17 08:09 UTC, dvorakjan approved these changes

2022-03-17 08:10 UTC, merged